1.Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.

In [1]:
import numpy as np

vec = np.arange(1, 21)
print(vec)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


2.Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.

In [2]:
import numpy as np

mat_ones = np.ones((4, 4), dtype=int)
print(mat_ones)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


3.Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.

In [3]:
import numpy as np

arr_5x5 = np.random.uniform(-1, 1, size=(5, 5))
print(arr_5x5)

[[ 0.40477343  0.06265335  0.87164944  0.0991474   0.2511515 ]
 [ 0.38576801  0.42018148 -0.03595028  0.70161279  0.74385493]
 [-0.08072417  0.06248273 -0.61799692 -0.0857275   0.09773877]
 [-0.9104873   0.22500323 -0.40605348  0.00115368  0.98416982]
 [ 0.89894403  0.15631221 -0.43633208  0.73628752  0.73852006]]


4.Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [4]:
import numpy as np

arr_3x3 = np.random.random((3, 3))
print(arr_3x3)

[[0.70224619 0.16588831 0.97538378]
 [0.23623914 0.99608017 0.02103763]
 [0.95205445 0.86515899 0.47767229]]


5.Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [5]:
import numpy as np

a = np.random.randint(1, 21, size=6)
b = np.random.randint(1, 21, size=6)

print("a =", a)
print("b =", b)
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)

a = [17 18 11  2  6 11]
b = [ 3 19  7  8  8  5]
a + b = [20 37 18 10 14 16]
a - b = [14 -1  4 -6 -2  6]
a * b = [ 51 342  77  16  48  55]


6.Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

In [6]:
import numpy as np

m1 = np.random.randint(1, 6, size=(3, 2))
m2 = np.random.randint(1, 6, size=(2, 4))

prod = m1 @ m2  # або np.matmul(m1, m2)

print("m1:\n", m1)
print("m2:\n", m2)
print("m1 @ m2:\n", prod)

m1:
 [[2 3]
 [4 2]
 [2 2]]
m2:
 [[1 3 1 5]
 [4 5 5 2]]
m1 @ m2:
 [[14 21 17 16]
 [12 22 14 24]
 [10 16 12 14]]


7.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [7]:
import numpy as np

m = np.random.random((3, 3))
mt = m.T

print("m:\n", m)
print("m.T:\n", mt)

m:
 [[0.34483025 0.43717293 0.70038418]
 [0.97076807 0.82112186 0.69013663]
 [0.99998071 0.59743553 0.2357367 ]]
m.T:
 [[0.34483025 0.97076807 0.99998071]
 [0.43717293 0.82112186 0.59743553]
 [0.70038418 0.69013663 0.2357367 ]]


8.Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [8]:
import numpy as np

x = np.random.randint(1, 11, size=(3, 3))
y = np.random.randint(1, 11, size=(3, 3))

diff = x - y

print("x:\n", x)
print("y:\n", y)
print("x - y:\n", diff)

x:
 [[10  8  7]
 [ 8  2  4]
 [ 1  5  1]]
y:
 [[ 3  6 10]
 [ 2  8  4]
 [10  6  6]]
x - y:
 [[ 7  2 -3]
 [ 6 -6  0]
 [-9 -1 -5]]


9.Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.

In [9]:
import numpy as np

p = np.random.randint(-5, 6, size=(3, 3))
q = np.random.randint(-5, 6, size=(3, 3))

elem_prod = p * q

print("p:\n", p)
print("q:\n", q)
print("p * q (element-wise):\n", elem_prod)

p:
 [[ 0  1 -5]
 [ 0 -5  4]
 [ 1  4 -5]]
q:
 [[ 2  4 -1]
 [ 2  4 -1]
 [-3  2  5]]
p * q (element-wise):
 [[  0   4   5]
 [  0 -20  -4]
 [ -3   8 -25]]


10.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [10]:
import numpy as np

m = np.random.uniform(-1, 1, size=(3, 3))
row_sums_col = m.sum(axis=1).reshape(-1, 1)

print("m:\n", m)
print("row sums (column vector):\n", row_sums_col)

m:
 [[-0.8574742  -0.16778027  0.23198313]
 [-0.43422023 -0.43782148  0.93857813]
 [ 0.16997482  0.6371576   0.76620186]]
row sums (column vector):
 [[-0.79327133]
 [ 0.06653641]
 [ 1.57333428]]
